/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exemplotela;

import javax.swing.JOptionPane;

/**
 *
 * @author christian.fguimaraes
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        
        //centralizar tela 
        this.setLocationRelativeTo(null);
        
        //Maximizar
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMensagemSimples = new javax.swing.JButton();
        btnEntradaSimples = new javax.swing.JButton();
        btnConfirmacao = new javax.swing.JButton();
        btnOutrasOpcoes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDialago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnMensagemSimples.setBackground(new java.awt.Color(204, 204, 204));
        btnMensagemSimples.setText("Mensagem Simples");
        btnMensagemSimples.setToolTipText("");
        btnMensagemSimples.setActionCommand("Mensagemm Simples");
        btnMensagemSimples.setPreferredSize(new java.awt.Dimension(140, 25));
        btnMensagemSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensagemSimplesActionPerformed(evt);
            }
        });

        btnEntradaSimples.setBackground(new java.awt.Color(204, 204, 204));
        btnEntradaSimples.setText("Entrada Simples");
        btnEntradaSimples.setPreferredSize(new java.awt.Dimension(140, 25));
        btnEntradaSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaSimplesActionPerformed(evt);
            }
        });

        btnConfirmacao.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirmacao.setText("Confirmação");
        btnConfirmacao.setMaximumSize(new java.awt.Dimension(108, 23));
        btnConfirmacao.setPreferredSize(new java.awt.Dimension(108, 23));
        btnConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacaoActionPerformed(evt);
            }
        });

        btnOutrasOpcoes.setBackground(new java.awt.Color(204, 204, 204));
        btnOutrasOpcoes.setText("Outras Opções");
        btnOutrasOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrasOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMensagemSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOutrasOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntradaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnMensagemSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnEntradaSimples, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnOutrasOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atalhos"));
        jPanel2.setPreferredSize(new java.awt.Dimension(236, 23));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        btnDialago.setText("Dialago");
        btnDialago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnDialago, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnDialago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacaoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this, 
                                      "Deseja confirma", 
                                      "Caixa de Confirmaçaõ", 
                                      JOptionPane.YES_NO_CANCEL_OPTION);
    }//GEN-LAST:event_btnConfirmacaoActionPerformed

    private void btnOutrasOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrasOpcoesActionPerformed
        // TODO add your handling code here:
        int time = JOptionPane.showOptionDialog(rootPane, 
                                     "Qual é o Melhor time do Brasil ? ",
                                     "Melhor time do Brasil", 
                                      JOptionPane.DEFAULT_OPTION, 
                                     JOptionPane.QUESTION_MESSAGE, 
                                     null, 
                                     new String[]{"Palmeiras", "Flamengo", "Corinthians"}, 
                                     "Corinthians");
        
        if(time == 2)
            JOptionPane.showMessageDialog(rootPane, "Você está certo!!");
         else 
            JOptionPane.showOptionDialog(rootPane, 
                                     "Qual é o Melhor time do Brasil ? ",
                                     "Melhor time do Brasil", 
                                      JOptionPane.DEFAULT_OPTION, 
                                     JOptionPane.QUESTION_MESSAGE, 
                                     null, 
                                     new String[]{"Palmeiras", "Flamengo", "Corinthians"}, 
                                     "Corinthians");   
    }//GEN-LAST:event_btnOutrasOpcoesActionPerformed

    private void btnMensagemSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensagemSimplesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Mensagem de Alerta");
        
    }//GEN-LAST:event_btnMensagemSimplesActionPerformed

    private void btnEntradaSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaSimplesActionPerformed
        // TODO add your handling code here:
       String nome = JOptionPane.showInputDialog("Digite seu Nome: ");
       
       JOptionPane.showMessageDialog(rootPane, "Bem Vindo " + nome);
    }//GEN-LAST:event_btnEntradaSimplesActionPerformed

    private void btnDialagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialagoActionPerformed
        // TODO add your handling code here:
        CadastroClienteDialogo dialago1 = new CadastroClienteDialogo(this, true);
        
        dialago1.setVisible(true);
    }//GEN-LAST:event_btnDialagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmacao;
    private javax.swing.JButton btnDialago;
    private javax.swing.JButton btnEntradaSimples;
    private javax.swing.JButton btnMensagemSimples;
    private javax.swing.JButton btnOutrasOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
